### ISSUE TITLE
Accepts string inputs but gives garbled output

### ISSUE THREAD

**Issue by dbussert** [proj4js/mgrs#12]
I integrated mgrs into a bot I'm making and initially got bad results because the inputs were strings.  It works correctly after doing a parseFloat on the input, but mgrs should either do a parseFloat or a typeof check on the input and throw an error.

```
convert 11.1, 21.1 to mgrs
MGRS: 4PҐU1790008802 from Lat, Lon: 11.1, 21.1
convert 34.1, -77.1 to mgrs
MGRS: -12SrR6531190495 from Lat, Lon: 34.1, -77.1
terabot convert 34, -77 to mgrs
MGRS: -12863S  300001e+23 from Lat, Lon: 34, -77
```

**Comment by DanielJDufour** [comment]
Good point.  A new maintainer here :wave: I added this to a new issue to validate input: https://github.com/proj4js/mgrs/issues/32

**Comment by DanielJDufour** [comment]
This was fixed with https://github.com/proj4js/mgrs/pull/36.  Let me know if you have any more issues! :-)
