### ISSUE TITLE
Wrong locations?

### ISSUE THREAD

**Issue by desean1625** [proj4js/mgrs#18]
loc = [13.140,29.857];
mgrs.forward(loc,5); //"33RUP2033504392"

All other online converters show 35PRQ0975854374

or
loc = [84.1065, 79.189];
mgrs.forward(loc,5); //"45XVH3943592571"

All other online converters show ZJF4324977165

**Comment by calvinmetcalf** [comment]
link to the online converter?

**Comment by desean1625** [comment]
http://www.earthpoint.us/Convert.aspx
and
http://legallandconverter.com/cgi-bin/shopmgrs3.cgi

**Comment by ccruz09** [comment]
@desean1625 The utility uses the format of [longitude, latitude]. I think you are using the first value on your coordinates as latitude and the second as longitude. Switch them and you should get the same mgrs position as the online converters.

**Comment by desean1625** [comment]
RTFM.. got it. I'm just use to [lat,long] I didn't even think about it.

FYI mgrs.forward(["29.857","13.14"]) = "5P҈D2638262350"
mgrs.forward([29.857,13.14]) = "35PRQ0975854375"
might want to change
```js
exports.forward = function(ll, accuracy) {
  accuracy = accuracy || 5; // default accuracy 1m
  return encode(LLtoUTM({
    lat: ll[1],
    lon: ll[0]
  }), accuracy);
};
```
 to
```js
exports.forward = function(ll, accuracy) {
  accuracy = accuracy || 5; // default accuracy 1m
  return encode(LLtoUTM({
    lat: Number(ll[1]),
    lon: Number(ll[0])
  }), accuracy);
};
```
