### ISSUE TITLE
Conversion Issue

### ISSUE THREAD

**Issue by Xeverus01** [proj4js/mgrs#26]
Hey! Thanks for the script so much - we really need it but I'm having some trouble getting the result to convert.  Ex.

this.Longitude = 36.810227
this.Latitude = -1.233558

var latlong = [this.Longitude,this.Latitude];
retStr = mgrs.forward(latlong);
alert(retStr);

Results in: 7Mԡ?0881866178

The MGRS conversion should be 37M BU 56329 63554.  Any ideas as to why its creating a bogus character?

**Comment by Xeverus01** [comment]
Ah, figured it out.  Needs to be an integer. parseFloat(this.Longitude).  I'll leave this here in case others have the same question - thanks for such a great script.

**Comment by DanielJDufour** [comment]
Great catch @Xeverus01 .  A new maintainer here! :-) I'm going to close this issue, but I have added it to the referenced issue #32 , to alert users when they pass in [lon, lat] as an array of strings instead of an array of numbers.  Thank you!
