### ISSUE TITLE
Run Automated Tests with Pull Requests

### ISSUE THREAD

**Issue by DanielJDufour** [proj4js/mgrs#40]
I'd recommend using Travis CI.  I know Travis CI isn't perfect, but I'd do it to maintain consistency with https://github.com/proj4js/proj4js and because it's easier to run tests on multiple version on NodeJS than Circle CI.  Any objections? @ahocevar @calvinmetcalf

**Comment by DanielJDufour** [comment]
Hi @calvinmetcalf and @ahocevar , could one of you activate the proj4js/mgrs repo in Travis CI, so we can have automated tests run on each pull request?  I think the link is https://travis-ci.org/proj4js/mgrs  I created a .travis.yml file here: https://github.com/proj4js/mgrs/blob/master/.travis.yml

Alternatively, if you'd like to make me an admin for this repository, I can set up the automated testing myself.

Thank you! :-)

**Comment by ahocevar** [comment]
@DanielJDufour I have just turned on TravisCI for proj4js/mgrs.

**Comment by DanielJDufour** [comment]
Awesome. Thank you!
