### ISSUE TITLE
MGRS.inverse doesn't handle mgrs coordinates without northing and easting

### ISSUE THREAD

**Issue by dswen** [proj4js/mgrs#6]
```inverse``` calculates ```bbox = UTMtoLL(decode(mgrsString))```. For an ```mgrsString``` such as ```"18TWN"```, ```decode``` returns an object without the ```accuracy``` property defined. Then when ```UTMtoLL``` creates the object to be returned, it creates a ```{lat: x, lon: y}``` rather than ```{left: x1, right: x2, top: y1, bottom: y2}```. ```inverse``` then returns ```[bbox.left, bbox.bottom, bbox.right, bbox.top]``` which is ```[undefined, undefined, undefined, undefined]``` for a ```bbox``` that only has the ```lat``` and ```lon``` properties. I don't know the best way to fix this, but my suggestion would be to have ```UTMtoLL``` always return the same type of object. It's somewhat confusing to have it return one type of object in one case, and another type of object in another case.

There is a workaround, which is to append ```"00"``` to the input string, but it would be better if that were not necessary.

**Comment by calvinmetcalf** [comment]
done published on npm as 0.0.1

**Comment by dswen** [comment]
Thank you for your quick response.
