### ISSUE TITLE
Defaul function of mgrs.js

### ISSUE THREAD

**Issue by JanTrunecek** [proj4js/mgrs#86]
How can I make or where do I get a default function mgrs that proj4 requiers me to to have.

import mgrs from "../../mgrs/mgrs.js";

proj4.mgrs = mgrs;

I'm held up on this for weeks and cant find a way to fix it anywhere on the internet.

**Comment by ahocevar** [comment]
```js
import mgrs from "mgrs";

proj4.mgrs = mgrs;
```
Does that work for you?

**Comment by JanTrunecek** [comment]
The proble is I'm using pycharm and dont have any buil plug in so I'm doing everything manually as well as dependencies so I have to link thing manually

**Comment by JanTrunecek** [comment]
Maybe what is the main file to link in this liberary? I assumed its this on on the bassis that its the only .js file with actuall code

**Comment by ahocevar** [comment]
If you're looking for the CommonJS file, that's `dist/mgrs.js` in the mgrs package.

**Comment by JanTrunecek** [comment]
I was using the mgrj.js from the main directory so I changed them but this one doesnt have a defaul export either. It seams I will have to get some tool to instal the lib for me. Thank you for ur time.

**Comment by ahocevar** [comment]
`mgrs.js` in the root folder requires node or a bundler, and it only has named exports.
